[package]
name = "coconuts"
version = "0.1.0"
authors = ["Brian Anderson <andersrb@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "2.0.0"
serde = "1.0.116"

[profile.dev]
opt-level = 1
debug = false
panic = "abort"
